# Project information
site_name: Zeedam regels
site_url: 'https://robbe-delsoir.github.io/wet-en-regelgeving/'
site_description: 'Zeedam regels'
site_author: 'Zeedam'

# Copyright
copyright: Copyright &copy; 2021 Zeedam

# Repository
repo_url: 'https://github.com/robbe-delsoir/wet-en-regelgeving'
repo_name: 'Mosterdgas/Zeedam-Regels'


# Configuration
theme: mkdocs
  name: readthedocs
    analytics:
        gtag: G-ABC123

  favicon: img/Zeedam.jpg
  logo: img/Zeedam.jpg
  custom_dir: docs/overrides
  language: nl
plugins:
  - git-revision-date-localized:
      type: timeago
      time_zone: Europe/Amsterdam
      locale: nl
      fallback_to_build_date: false
  - search:
      lang: nl
markdown_extensions:
  - admonition
  - attr_list
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - javascripts/tables.js
nav:
  - Home: index.md
  - Berechting: Berechting.md
  - Criminaliteit: Criminaliteit.md
  - Offroad: Offroad.md
  - Eiland: Eiland.md
